// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodServer
{
    // Engine object used for calling engine methods
    protected GodotObject _object;

    public FmodServer() : this(NativeName)
    {
    }
    protected FmodServer(StringName @class) : this(ClassDB.Instantiate(@class))
    {
    }
    protected FmodServer(Variant variant) : this((GodotObject)variant)
    {
    }
    protected FmodServer([NotNull] GodotObject @object)
    {
        _object = @object;
    }

    public static implicit operator GodotObject(FmodServer self) => self?._object;
    public static implicit operator Variant(FmodServer self) => (Variant)(self?._object);
    public static explicit operator FmodServer(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

    public class PropertyName : GodotObject.PropertyName
    {

    }

    public class MethodName : GodotObject.MethodName
    {
        public static readonly StringName Init = "init";
        public static readonly StringName Update = "update";
        public static readonly StringName Shutdown = "shutdown";
        public static readonly StringName SetSoftwareFormat = "set_software_format";
        public static readonly StringName SetSound3dSettings = "set_sound_3D_settings";
        public static readonly StringName SetSystemDspBufferSize = "set_system_dsp_buffer_size";
        public static readonly StringName GetSystemDspBufferSettings = "get_system_dsp_buffer_settings";
        public static readonly StringName GetSystemDspBufferLength = "get_system_dsp_buffer_length";
        public static readonly StringName GetSystemDspNumBuffers = "get_system_dsp_num_buffers";
        public static readonly StringName CheckVcaGuid = "check_vca_guid";
        public static readonly StringName CheckVcaPath = "check_vca_path";
        public static readonly StringName CheckBusGuid = "check_bus_guid";
        public static readonly StringName CheckBusPath = "check_bus_path";
        public static readonly StringName CheckEventGuid = "check_event_guid";
        public static readonly StringName CheckEventPath = "check_event_path";
        public static readonly StringName GetVcaFromGuid = "get_vca_from_guid";
        public static readonly StringName GetVca = "get_vca";
        public static readonly StringName GetBusFromGuid = "get_bus_from_guid";
        public static readonly StringName GetBus = "get_bus";
        public static readonly StringName GetEventFromGuid = "get_event_from_guid";
        public static readonly StringName GetEvent = "get_event";
        public static readonly StringName GetEventGuid = "get_event_guid";
        public static readonly StringName GetEventPath = "get_event_path";
        public static readonly StringName GetAllVca = "get_all_vca";
        public static readonly StringName GetAllBuses = "get_all_buses";
        public static readonly StringName GetAllEventDescriptions = "get_all_event_descriptions";
        public static readonly StringName GetAllBanks = "get_all_banks";
        public static readonly StringName GetAvailableDrivers = "get_available_drivers";
        public static readonly StringName GetDriver = "get_driver";
        public static readonly StringName SetDriver = "set_driver";
        public static readonly StringName GetPerformanceData = "get_performance_data";
        public static readonly StringName SetGlobalParameterByName = "set_global_parameter_by_name";
        public static readonly StringName SetGlobalParameterByNameWithLabel = "set_global_parameter_by_name_with_label";
        public static readonly StringName GetGlobalParameterByName = "get_global_parameter_by_name";
        public static readonly StringName SetGlobalParameterById = "set_global_parameter_by_id";
        public static readonly StringName SetGlobalParameterByIdWithLabel = "set_global_parameter_by_id_with_label";
        public static readonly StringName GetGlobalParameterById = "get_global_parameter_by_id";
        public static readonly StringName GetGlobalParameterDescByName = "get_global_parameter_desc_by_name";
        public static readonly StringName GetGlobalParameterDescById = "get_global_parameter_desc_by_id";
        public static readonly StringName GetGlobalParameterDescCount = "get_global_parameter_desc_count";
        public static readonly StringName GetGlobalParameterDescList = "get_global_parameter_desc_list";
        public static readonly StringName AddListener = "add_listener";
        public static readonly StringName RemoveListener = "remove_listener";
        public static readonly StringName SetListenerNumber = "set_listener_number";
        public static readonly StringName GetListenerNumber = "get_listener_number";
        public static readonly StringName GetListenerWeight = "get_listener_weight";
        public static readonly StringName SetListenerWeight = "set_listener_weight";
        public static readonly StringName GetListenerTransform3d = "get_listener_transform3d";
        public static readonly StringName GetListenerTransform2d = "get_listener_transform2d";
        public static readonly StringName GetListener3dVelocity = "get_listener_3d_velocity";
        public static readonly StringName GetListener2dVelocity = "get_listener_2d_velocity";
        public static readonly StringName SetListenerTransform3d = "set_listener_transform3d";
        public static readonly StringName SetListenerTransform2d = "set_listener_transform2d";
        public static readonly StringName SetListenerLock = "set_listener_lock";
        public static readonly StringName GetListenerLock = "get_listener_lock";
        public static readonly StringName GetObjectAttachedToListener = "get_object_attached_to_listener";
        public static readonly StringName LoadBank = "load_bank";
        public static readonly StringName WaitForAllLoads = "wait_for_all_loads";
        public static readonly StringName BanksStillLoading = "banks_still_loading";
        public static readonly StringName LoadPlugin = "load_plugin";
        public static readonly StringName UnloadPlugin = "unload_plugin";
        public static readonly StringName IsPluginLoaded = "is_plugin_loaded";
        public static readonly StringName LoadFileAsSound = "load_file_as_sound";
        public static readonly StringName LoadFileAsMusic = "load_file_as_music";
        public static readonly StringName UnloadFile = "unload_file";
        public static readonly StringName CreateEventInstanceWithGuid = "create_event_instance_with_guid";
        public static readonly StringName CreateEventInstance = "create_event_instance";
        public static readonly StringName CreateEventInstanceFromDescription = "create_event_instance_from_description";
        public static readonly StringName PlayOneShotUsingGuid = "play_one_shot_using_guid";
        public static readonly StringName PlayOneShot = "play_one_shot";
        public static readonly StringName PlayOneShotUsingEventDescription = "play_one_shot_using_event_description";
        public static readonly StringName PlayOneShotUsingGuidWithParams = "play_one_shot_using_guid_with_params";
        public static readonly StringName PlayOneShotWithParams = "play_one_shot_with_params";
        public static readonly StringName PlayOneShotUsingEventDescriptionWithParams = "play_one_shot_using_event_description_with_params";
        public static readonly StringName PlayOneShotUsingGuidAttached = "play_one_shot_using_guid_attached";
        public static readonly StringName PlayOneShotAttached = "play_one_shot_attached";
        public static readonly StringName PlayOneShotUsingEventDescriptionAttached = "play_one_shot_using_event_description_attached";
        public static readonly StringName PlayOneShotUsingGuidAttachedWithParams = "play_one_shot_using_guid_attached_with_params";
        public static readonly StringName PlayOneShotAttachedWithParams = "play_one_shot_attached_with_params";
        public static readonly StringName PlayOneShotUsingEventDescriptionAttachedWithParams = "play_one_shot_using_event_description_attached_with_params";
        public static readonly StringName PauseAllEvents = "pause_all_events";
        public static readonly StringName UnpauseAllEvents = "unpause_all_events";
        public static readonly StringName MuteAllEvents = "mute_all_events";
        public static readonly StringName UnmuteAllEvents = "unmute_all_events";
        public static readonly StringName CreateSoundInstance = "create_sound_instance";
    }

    public class SignalName : GodotObject.SignalName
    {

    }

    private static readonly StringName NativeName = "FmodServer";

    #region Integer Constants

    public const long FmodInit3dRighthanded = 4L;

    public const long FmodInitChannelDistancefilter = 512L;

    public const long FmodInitChannelLowpass = 256L;

    public const long FmodInitGeometryUseclosest = 262144L;

    public const long FmodInitMixFromUpdate = 2L;

    public const long FmodInitNormal = 0L;

    public const long FmodInitPreferDolbyDownmix = 524288L;

    public const long FmodInitProfileEnable = 65536L;

    public const long FmodInitProfileMeterAll = 2097152L;

    public const long FmodInitStreamFromUpdate = 1L;

    public const long FmodInitThreadUnsafe = 1048576L;

    public const long FmodInitVol0BecomesVirtual = 131072L;

    public const long FmodStudioInitNormal = 0L;

    public const long FmodStudioInitLiveupdate = 1L;

    public const long FmodStudioInitAllowMissingPlugins = 2L;

    public const long FmodStudioInitSynchronousUpdate = 4L;

    public const long FmodStudioInitDeferredCallbacks = 8L;

    public const long FmodStudioInitLoadFromUpdate = 16L;

    public const long FmodSpeakermode5point1 = 6L;

    public const long FmodSpeakermode7point1 = 7L;

    public const long FmodSpeakermode7point1point4 = 8L;

    public const long FmodSpeakermodeDefault = 0L;

    public const long FmodSpeakermodeMax = 9L;

    public const long FmodSpeakermodeMono = 2L;

    public const long FmodSpeakermodeQuad = 4L;

    public const long FmodSpeakermodeRaw = 1L;

    public const long FmodSpeakermodeStereo = 3L;

    public const long FmodSpeakermodeSurround = 5L;

    public const long FmodStudioLoadBankNormal = 0L;

    public const long FmodStudioLoadBankNonblocking = 1L;

    public const long FmodStudioLoadBankDecompressSamples = 2L;

    public const long Fmod2d = 8L;

    public const long Fmod3d = 16L;

    public const long Fmod3dCustomrolloff = 67108864L;

    public const long Fmod3dHeadrelative = 262144L;

    public const long Fmod3dIgnoregeometry = 1073741824L;

    public const long Fmod3dInverserolloff = 1048576L;

    public const long Fmod3dInversetaperedrolloff = 8388608L;

    public const long Fmod3dLinearrolloff = 2097152L;

    public const long Fmod3dLinearsquarerolloff = 4194304L;

    public const long Fmod3dWorldrelative = 524288L;

    public const long FmodAccuratetime = 16384L;

    public const long FmodCreatecompressedsample = 512L;

    public const long FmodCreatesample = 256L;

    public const long FmodCreatestream = 128L;

    public const long FmodDefault = 0L;

    public const long FmodIgnoretags = 33554432L;

    public const long FmodLoopBidi = 4L;

    public const long FmodLoopNormal = 2L;

    public const long FmodLoopOff = 1L;

    public const long FmodLowmem = 134217728L;

    public const long FmodMpegsearch = 32768L;

    public const long FmodNonblocking = 65536L;

    public const long FmodOpenmemory = 2048L;

    public const long FmodOpenmemoryPoint = 268435456L;

    public const long FmodOpenonly = 8192L;

    public const long FmodOpenraw = 4096L;

    public const long FmodOpenuser = 1024L;

    public const long FmodUnique = 131072L;

    public const long FmodVirtualPlayfromstart = 2147483648L;

    public const long FmodStudioStopAllowfadeout = 0L;

    public const long FmodStudioStopImmediate = 1L;

    public const long FmodStudioStopForceint = 65536L;

    public const long FmodStudioSystemCallbackPreupdate = 1L;

    public const long FmodStudioSystemCallbackPostupdate = 2L;

    public const long FmodStudioSystemCallbackBankUnload = 4L;

    public const long FmodStudioSystemCallbackLiveupdateConnected = 8L;

    public const long FmodStudioSystemCallbackLiveupdateDisconnected = 16L;

    public const long FmodStudioSystemCallbackAll = 4294967295L;

    public const long FmodStudioEventCallbackCreated = 1L;

    public const long FmodStudioEventCallbackDestroyed = 2L;

    public const long FmodStudioEventCallbackStarting = 4L;

    public const long FmodStudioEventCallbackStarted = 8L;

    public const long FmodStudioEventCallbackRestarted = 16L;

    public const long FmodStudioEventCallbackStopped = 32L;

    public const long FmodStudioEventCallbackStartFailed = 64L;

    public const long FmodStudioEventCallbackCreateProgrammerSound = 128L;

    public const long FmodStudioEventCallbackDestroyProgrammerSound = 256L;

    public const long FmodStudioEventCallbackPluginCreated = 512L;

    public const long FmodStudioEventCallbackPluginDestroyed = 1024L;

    public const long FmodStudioEventCallbackTimelineMarker = 2048L;

    public const long FmodStudioEventCallbackTimelineBeat = 4096L;

    public const long FmodStudioEventCallbackSoundPlayed = 8192L;

    public const long FmodStudioEventCallbackSoundStopped = 16384L;

    public const long FmodStudioEventCallbackRealToVirtual = 32768L;

    public const long FmodStudioEventCallbackVirtualToReal = 65536L;

    public const long FmodStudioEventCallbackStartEventCommand = 131072L;

    public const long FmodStudioEventCallbackNestedTimelineBeat = 262144L;

    public const long FmodStudioEventCallbackAll = 4294967295L;

    public const long FmodStudioLoadingStateUnloading = 0L;

    public const long FmodStudioLoadingStateUnloaded = 1L;

    public const long FmodStudioLoadingStateLoading = 2L;

    public const long FmodStudioLoadingStateLoaded = 3L;

    public const long FmodStudioLoadingStateError = 4L;

    public const long FmodStudioLoadingStateForceint = 65536L;

    public const long FmodStudioPlaybackPlaying = 0L;

    public const long FmodStudioPlaybackSustaining = 1L;

    public const long FmodStudioPlaybackStopped = 2L;

    public const long FmodStudioPlaybackStarting = 3L;

    public const long FmodStudioPlaybackStopping = 4L;

    public const long FmodStudioPlaybackForceint = 65536L;

    #endregion

    #region Methods

    public void Init(FmodGeneralSettings @p_settings)
    {
        _object.Call(MethodName.Init, @p_settings);
    }

    public void Update()
    {
        _object.Call(MethodName.Update);
    }

    public void Shutdown()
    {
        _object.Call(MethodName.Shutdown);
    }

    public void SetSoftwareFormat(FmodSoftwareFormatSettings @p_settings)
    {
        _object.Call(MethodName.SetSoftwareFormat, @p_settings);
    }

    public void SetSound3dSettings(FmodSound3DSettings @p_settings)
    {
        _object.Call(MethodName.SetSound3dSettings, @p_settings);
    }

    public void SetSystemDspBufferSize(FmodDspSettings @dsp_settings)
    {
        _object.Call(MethodName.SetSystemDspBufferSize, @dsp_settings);
    }

    public FmodDspSettings GetSystemDspBufferSettings()
    {
        return (FmodDspSettings)_object.Call(MethodName.GetSystemDspBufferSettings);
    }

    public int GetSystemDspBufferLength()
    {
        return (int)_object.Call(MethodName.GetSystemDspBufferLength);
    }

    public int GetSystemDspNumBuffers()
    {
        return (int)_object.Call(MethodName.GetSystemDspNumBuffers);
    }

    public bool CheckVcaGuid(string @guid)
    {
        return (bool)_object.Call(MethodName.CheckVcaGuid, @guid);
    }

    public bool CheckVcaPath(string @cvaPath)
    {
        return (bool)_object.Call(MethodName.CheckVcaPath, @cvaPath);
    }

    public bool CheckBusGuid(string @guid)
    {
        return (bool)_object.Call(MethodName.CheckBusGuid, @guid);
    }

    public bool CheckBusPath(string @busPath)
    {
        return (bool)_object.Call(MethodName.CheckBusPath, @busPath);
    }

    public bool CheckEventGuid(string @guid)
    {
        return (bool)_object.Call(MethodName.CheckEventGuid, @guid);
    }

    public bool CheckEventPath(string @eventPath)
    {
        return (bool)_object.Call(MethodName.CheckEventPath, @eventPath);
    }

    public FmodVCA GetVcaFromGuid(string @guid)
    {
        return (FmodVCA)_object.Call(MethodName.GetVcaFromGuid, @guid);
    }

    public FmodVCA GetVca(string @cvaPath)
    {
        return (FmodVCA)_object.Call(MethodName.GetVca, @cvaPath);
    }

    public FmodBus GetBusFromGuid(string @guid)
    {
        return (FmodBus)_object.Call(MethodName.GetBusFromGuid, @guid);
    }

    public FmodBus GetBus(string @busPath)
    {
        return (FmodBus)_object.Call(MethodName.GetBus, @busPath);
    }

    public FmodEventDescription GetEventFromGuid(string @guid)
    {
        return (FmodEventDescription)_object.Call(MethodName.GetEventFromGuid, @guid);
    }

    public FmodEventDescription GetEvent(string @eventPath)
    {
        return (FmodEventDescription)_object.Call(MethodName.GetEvent, @eventPath);
    }

    public string GetEventGuid(string @event_path)
    {
        return (string)_object.Call(MethodName.GetEventGuid, @event_path);
    }

    public string GetEventPath(string @guid)
    {
        return (string)_object.Call(MethodName.GetEventPath, @guid);
    }

    public Godot.Collections.Array GetAllVca()
    {
        return (Godot.Collections.Array)_object.Call(MethodName.GetAllVca);
    }

    public Godot.Collections.Array GetAllBuses()
    {
        return (Godot.Collections.Array)_object.Call(MethodName.GetAllBuses);
    }

    public Godot.Collections.Array GetAllEventDescriptions()
    {
        return (Godot.Collections.Array)_object.Call(MethodName.GetAllEventDescriptions);
    }

    public Godot.Collections.Array GetAllBanks()
    {
        return (Godot.Collections.Array)_object.Call(MethodName.GetAllBanks);
    }

    public Godot.Collections.Array GetAvailableDrivers()
    {
        return (Godot.Collections.Array)_object.Call(MethodName.GetAvailableDrivers);
    }

    public int GetDriver()
    {
        return (int)_object.Call(MethodName.GetDriver);
    }

    public void SetDriver(int @id)
    {
        _object.Call(MethodName.SetDriver, @id);
    }

    public FmodPerformanceData GetPerformanceData()
    {
        return (FmodPerformanceData)_object.Call(MethodName.GetPerformanceData);
    }

    public void SetGlobalParameterByName(string @parameter_name, float @value)
    {
        _object.Call(MethodName.SetGlobalParameterByName, @parameter_name, @value);
    }

    public void SetGlobalParameterByNameWithLabel(string @parameter_name, string @label)
    {
        _object.Call(MethodName.SetGlobalParameterByNameWithLabel, @parameter_name, @label);
    }

    public float GetGlobalParameterByName(string @parameter_name)
    {
        return (float)_object.Call(MethodName.GetGlobalParameterByName, @parameter_name);
    }

    public void SetGlobalParameterById(int @parameter_id, float @value)
    {
        _object.Call(MethodName.SetGlobalParameterById, @parameter_id, @value);
    }

    public void SetGlobalParameterByIdWithLabel(int @parameter_id, string @label)
    {
        _object.Call(MethodName.SetGlobalParameterByIdWithLabel, @parameter_id, @label);
    }

    public float GetGlobalParameterById(int @parameter_id)
    {
        return (float)_object.Call(MethodName.GetGlobalParameterById, @parameter_id);
    }

    public Godot.Collections.Dictionary GetGlobalParameterDescByName(string @parameterName)
    {
        return (Godot.Collections.Dictionary)_object.Call(MethodName.GetGlobalParameterDescByName, @parameterName);
    }

    public Godot.Collections.Dictionary GetGlobalParameterDescById(int @parameter_id)
    {
        return (Godot.Collections.Dictionary)_object.Call(MethodName.GetGlobalParameterDescById, @parameter_id);
    }

    public int GetGlobalParameterDescCount()
    {
        return (int)_object.Call(MethodName.GetGlobalParameterDescCount);
    }

    public Godot.Collections.Array GetGlobalParameterDescList()
    {
        return (Godot.Collections.Array)_object.Call(MethodName.GetGlobalParameterDescList);
    }

    public void AddListener(int @index, Node @game_obj)
    {
        _object.Call(MethodName.AddListener, @index, @game_obj);
    }

    public void RemoveListener(int @index, Node @game_obj)
    {
        _object.Call(MethodName.RemoveListener, @index, @game_obj);
    }

    public void SetListenerNumber(int @listenerNumber)
    {
        _object.Call(MethodName.SetListenerNumber, @listenerNumber);
    }

    public int GetListenerNumber()
    {
        return (int)_object.Call(MethodName.GetListenerNumber);
    }

    public float GetListenerWeight(int @index)
    {
        return (float)_object.Call(MethodName.GetListenerWeight, @index);
    }

    public void SetListenerWeight(int @index, float @weight)
    {
        _object.Call(MethodName.SetListenerWeight, @index, @weight);
    }

    public Godot.Transform3D GetListenerTransform3d(int @index)
    {
        return (Godot.Transform3D)_object.Call(MethodName.GetListenerTransform3d, @index);
    }

    public Godot.Transform2D GetListenerTransform2d(int @index)
    {
        return (Godot.Transform2D)_object.Call(MethodName.GetListenerTransform2d, @index);
    }

    public Godot.Vector3 GetListener3dVelocity(int @index)
    {
        return (Godot.Vector3)_object.Call(MethodName.GetListener3dVelocity, @index);
    }

    public Godot.Vector2 GetListener2dVelocity(int @index)
    {
        return (Godot.Vector2)_object.Call(MethodName.GetListener2dVelocity, @index);
    }

    public void SetListenerTransform3d(int @index, Godot.Transform3D @transform)
    {
        _object.Call(MethodName.SetListenerTransform3d, @index, @transform);
    }

    public void SetListenerTransform2d(int @index, Godot.Transform2D @transform)
    {
        _object.Call(MethodName.SetListenerTransform2d, @index, @transform);
    }

    public void SetListenerLock(int @index, bool @isLocked)
    {
        _object.Call(MethodName.SetListenerLock, @index, @isLocked);
    }

    public bool GetListenerLock(int @index)
    {
        return (bool)_object.Call(MethodName.GetListenerLock, @index);
    }

    public GodotObject GetObjectAttachedToListener(int @index)
    {
        return (GodotObject)_object.Call(MethodName.GetObjectAttachedToListener, @index);
    }

    public FmodBank LoadBank(string @pathToBank, int @flag)
    {
        return (FmodBank)_object.Call(MethodName.LoadBank, @pathToBank, @flag);
    }

    public void WaitForAllLoads()
    {
        _object.Call(MethodName.WaitForAllLoads);
    }

    public bool BanksStillLoading()
    {
        return (bool)_object.Call(MethodName.BanksStillLoading);
    }

    public int LoadPlugin(string @p_plugin_path, int @p_priority = 0)
    {
        return (int)_object.Call(MethodName.LoadPlugin, @p_plugin_path, @p_priority);
    }

    public void UnloadPlugin(int @p_plugin_handle)
    {
        _object.Call(MethodName.UnloadPlugin, @p_plugin_handle);
    }

    public bool IsPluginLoaded(int @p_plugin_handle)
    {
        return (bool)_object.Call(MethodName.IsPluginLoaded, @p_plugin_handle);
    }

    public FmodFile LoadFileAsSound(string @path)
    {
        return (FmodFile)_object.Call(MethodName.LoadFileAsSound, @path);
    }

    public FmodFile LoadFileAsMusic(string @path)
    {
        return (FmodFile)_object.Call(MethodName.LoadFileAsMusic, @path);
    }

    public void UnloadFile(string @path)
    {
        _object.Call(MethodName.UnloadFile, @path);
    }

    public FmodEvent CreateEventInstanceWithGuid(string @guid)
    {
        return (FmodEvent)_object.Call(MethodName.CreateEventInstanceWithGuid, @guid);
    }

    public FmodEvent CreateEventInstance(string @eventPath)
    {
        return (FmodEvent)_object.Call(MethodName.CreateEventInstance, @eventPath);
    }

    public FmodEvent CreateEventInstanceFromDescription(FmodEventDescription @eventPath)
    {
        return (FmodEvent)_object.Call(MethodName.CreateEventInstanceFromDescription, @eventPath);
    }

    public void PlayOneShotUsingGuid(string @guid)
    {
        _object.Call(MethodName.PlayOneShotUsingGuid, @guid);
    }

    public void PlayOneShot(string @event_name)
    {
        _object.Call(MethodName.PlayOneShot, @event_name);
    }

    public void PlayOneShotUsingEventDescription(FmodEventDescription @event_description)
    {
        _object.Call(MethodName.PlayOneShotUsingEventDescription, @event_description);
    }

    public void PlayOneShotUsingGuidWithParams(string @guid, Godot.Collections.Dictionary @parameters)
    {
        _object.Call(MethodName.PlayOneShotUsingGuidWithParams, @guid, @parameters);
    }

    public void PlayOneShotWithParams(string @event_name, Godot.Collections.Dictionary @parameters)
    {
        _object.Call(MethodName.PlayOneShotWithParams, @event_name, @parameters);
    }

    public void PlayOneShotUsingEventDescriptionWithParams(FmodEventDescription @event_description, Godot.Collections.Dictionary @parameters)
    {
        _object.Call(MethodName.PlayOneShotUsingEventDescriptionWithParams, @event_description, @parameters);
    }

    public void PlayOneShotUsingGuidAttached(string @guid, Node @game_obj)
    {
        _object.Call(MethodName.PlayOneShotUsingGuidAttached, @guid, @game_obj);
    }

    public void PlayOneShotAttached(string @event_name, Node @game_obj)
    {
        _object.Call(MethodName.PlayOneShotAttached, @event_name, @game_obj);
    }

    public void PlayOneShotUsingEventDescriptionAttached(FmodEventDescription @event_description, Node @game_obj)
    {
        _object.Call(MethodName.PlayOneShotUsingEventDescriptionAttached, @event_description, @game_obj);
    }

    public void PlayOneShotUsingGuidAttachedWithParams(string @guid, Node @game_obj, Godot.Collections.Dictionary @parameters)
    {
        _object.Call(MethodName.PlayOneShotUsingGuidAttachedWithParams, @guid, @game_obj, @parameters);
    }

    public void PlayOneShotAttachedWithParams(string @event_name, Node @game_obj, Godot.Collections.Dictionary @parameters)
    {
        _object.Call(MethodName.PlayOneShotAttachedWithParams, @event_name, @game_obj, @parameters);
    }

    public void PlayOneShotUsingEventDescriptionAttachedWithParams(FmodEventDescription @event_description, Node @game_obj, Godot.Collections.Dictionary @parameters)
    {
        _object.Call(MethodName.PlayOneShotUsingEventDescriptionAttachedWithParams, @event_description, @game_obj, @parameters);
    }

    public void PauseAllEvents()
    {
        _object.Call(MethodName.PauseAllEvents);
    }

    public void UnpauseAllEvents()
    {
        _object.Call(MethodName.UnpauseAllEvents);
    }

    public void MuteAllEvents()
    {
        _object.Call(MethodName.MuteAllEvents);
    }

    public void UnmuteAllEvents()
    {
        _object.Call(MethodName.UnmuteAllEvents);
    }

    public FmodSound CreateSoundInstance(string @path)
    {
        return (FmodSound)_object.Call(MethodName.CreateSoundInstance, @path);
    }

    #endregion

    #region Inherited Methods

    public void Free()
    {
        _object.Free();
    }

    public string GetClass()
    {
        return _object.GetClass();
    }

    public bool IsClass(string @class)
    {
        return _object.IsClass(@class);
    }

    public void Set(Godot.StringName @property, Variant @value)
    {
        _object.Set(@property, @value);
    }

    public Variant Get(Godot.StringName @property)
    {
        return _object.Get(@property);
    }

    public void SetIndexed(Godot.NodePath @property_path, Variant @value)
    {
        _object.SetIndexed(@property_path, @value);
    }

    public Variant GetIndexed(Godot.NodePath @property_path)
    {
        return _object.GetIndexed(@property_path);
    }

    public Godot.Collections.Array<Godot.Collections.Dictionary> GetPropertyList()
    {
        return _object.GetPropertyList();
    }

    public Godot.Collections.Array<Godot.Collections.Dictionary> GetMethodList()
    {
        return _object.GetMethodList();
    }

    public bool PropertyCanRevert(Godot.StringName @property)
    {
        return _object.PropertyCanRevert(@property);
    }

    public Variant PropertyGetRevert(Godot.StringName @property)
    {
        return _object.PropertyGetRevert(@property);
    }

    public void Notification(int @what, bool @reversed = false)
    {
        _object.Notification(@what, @reversed);
    }

    public override string ToString()
    {
        return _object.ToString();
    }

    public ulong GetInstanceId()
    {
        return _object.GetInstanceId();
    }

    public void SetScript(Variant @script)
    {
        _object.SetScript(@script);
    }

    public Variant GetScript()
    {
        return _object.GetScript();
    }

    public void SetMeta(Godot.StringName @name, Variant @value)
    {
        _object.SetMeta(@name, @value);
    }

    public void RemoveMeta(Godot.StringName @name)
    {
        _object.RemoveMeta(@name);
    }

    public Variant GetMeta(Godot.StringName @name, Variant @default = default)
    {
        return _object.GetMeta(@name, @default);
    }

    public bool HasMeta(Godot.StringName @name)
    {
        return _object.HasMeta(@name);
    }

    public Godot.Collections.Array<StringName> GetMetaList()
    {
        return _object.GetMetaList();
    }

    public void AddUserSignal(string @signal, Godot.Collections.Array @arguments = null)
    {
        @arguments ??= new();
        _object.AddUserSignal(@signal, @arguments);
    }

    public bool HasUserSignal(Godot.StringName @signal)
    {
        return _object.HasUserSignal(@signal);
    }

    public void RemoveUserSignal(Godot.StringName @signal)
    {
        _object.RemoveUserSignal(@signal);
    }

    public Godot.Error EmitSignal(Godot.StringName @signal, params Variant[] varargs)
    {
        return _object.EmitSignal(@signal, varargs);
    }

    public Variant Call(Godot.StringName @method, params Variant[] varargs)
    {
        return _object.Call(@method, varargs);
    }

    public Variant CallDeferred(Godot.StringName @method, params Variant[] varargs)
    {
        return _object.CallDeferred(@method, varargs);
    }

    public void SetDeferred(Godot.StringName @property, Variant @value)
    {
        _object.SetDeferred(@property, @value);
    }

    public Variant Callv(Godot.StringName @method, Godot.Collections.Array @arg_array)
    {
        return _object.Callv(@method, @arg_array);
    }

    public bool HasMethod(Godot.StringName @method)
    {
        return _object.HasMethod(@method);
    }

    public int GetMethodArgumentCount(Godot.StringName @method)
    {
        return _object.GetMethodArgumentCount(@method);
    }

    public bool HasSignal(Godot.StringName @signal)
    {
        return _object.HasSignal(@signal);
    }

    public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalList()
    {
        return _object.GetSignalList();
    }

    public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalConnectionList(Godot.StringName @signal)
    {
        return _object.GetSignalConnectionList(@signal);
    }

    public Godot.Collections.Array<Godot.Collections.Dictionary> GetIncomingConnections()
    {
        return _object.GetIncomingConnections();
    }

    public Godot.Error Connect(Godot.StringName @signal, Godot.Callable @callable, uint @flags = (uint)0)
    {
        return _object.Connect(@signal, @callable, @flags);
    }

    public void Disconnect(Godot.StringName @signal, Godot.Callable @callable)
    {
        _object.Disconnect(@signal, @callable);
    }

    public bool IsConnected(Godot.StringName @signal, Godot.Callable @callable)
    {
        return _object.IsConnected(@signal, @callable);
    }

    public bool HasConnections(Godot.StringName @signal)
    {
        return _object.HasConnections(@signal);
    }

    public void SetBlockSignals(bool @enable)
    {
        _object.SetBlockSignals(@enable);
    }

    public bool IsBlockingSignals()
    {
        return _object.IsBlockingSignals();
    }

    public void NotifyPropertyListChanged()
    {
        _object.NotifyPropertyListChanged();
    }

    public void SetMessageTranslation(bool @enable)
    {
        _object.SetMessageTranslation(@enable);
    }

    public bool CanTranslateMessages()
    {
        return _object.CanTranslateMessages();
    }

    public string Tr(Godot.StringName @message, Godot.StringName @context = null)
    {
        @context ??= "";
        return _object.Tr(@message, @context);
    }

    public string TrN(Godot.StringName @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
    {
        @context ??= "";
        return _object.TrN(@message, @plural_message, @n, @context);
    }

    public Godot.StringName GetTranslationDomain()
    {
        return _object.GetTranslationDomain();
    }

    public void SetTranslationDomain(Godot.StringName @domain)
    {
        _object.SetTranslationDomain(@domain);
    }

    public bool IsQueuedForDeletion()
    {
        return _object.IsQueuedForDeletion();
    }

    public void CancelFree()
    {
        _object.CancelFree();
    }

    #endregion

    #region Inherited Signals

    public event Action ScriptChanged
    {
        add
        {
            Connect(SignalName.ScriptChanged, Callable.From(value));
        }
        remove
        {
            Disconnect(SignalName.ScriptChanged, Callable.From(value));
        }
    }

    public event Action PropertyListChanged
    {
        add
        {
            Connect(SignalName.PropertyListChanged, Callable.From(value));
        }
        remove
        {
            Disconnect(SignalName.PropertyListChanged, Callable.From(value));
        }
    }

    #endregion
}
