// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodEvent
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public FmodEvent() : this(NativeName)
	{
	}
	protected FmodEvent(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected FmodEvent(Variant variant) : this((RefCounted) variant)
	{
	}
	protected FmodEvent([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(FmodEvent self) => self?._object;
	public static implicit operator Variant(FmodEvent self) => self?._object;
	public static explicit operator FmodEvent(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{
		public static readonly StringName Paused = "paused";
		public static readonly StringName Pitch = "pitch";
		public static readonly StringName Volume = "volume";
		public static readonly StringName Position = "position";
		public static readonly StringName ListenerMask = "listener_mask";
		public static readonly StringName Transform2d = "transform_2d";
		public static readonly StringName Transform3d = "transform_3d";
	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName GetParameterByName = "get_parameter_by_name";
		public static readonly StringName SetParameterByName = "set_parameter_by_name";
		public static readonly StringName SetParameterByNameWithLabel = "set_parameter_by_name_with_label";
		public static readonly StringName GetParameterById = "get_parameter_by_id";
		public static readonly StringName SetParameterById = "set_parameter_by_id";
		public static readonly StringName SetParameterByIdWithLabel = "set_parameter_by_id_with_label";
		public static readonly StringName Start = "start";
		public static readonly StringName Stop = "stop";
		public static readonly StringName EventKeyOff = "event_key_off";
		public static readonly StringName GetPlaybackState = "get_playback_state";
		public static readonly StringName GetPaused = "get_paused";
		public static readonly StringName SetPaused = "set_paused";
		public static readonly StringName GetPitch = "get_pitch";
		public static readonly StringName SetPitch = "set_pitch";
		public static readonly StringName GetVolume = "get_volume";
		public static readonly StringName SetVolume = "set_volume";
		public static readonly StringName GetTimelinePosition = "get_timeline_position";
		public static readonly StringName SetTimelinePosition = "set_timeline_position";
		public static readonly StringName GetReverbLevel = "get_reverb_level";
		public static readonly StringName SetReverbLevel = "set_reverb_level";
		public static readonly StringName IsVirtual = "is_virtual";
		public static readonly StringName SetListenerMask = "set_listener_mask";
		public static readonly StringName GetListenerMask = "get_listener_mask";
		public static readonly StringName Set2dAttributes = "set_2d_attributes";
		public static readonly StringName Get2dAttributes = "get_2d_attributes";
		public static readonly StringName Set3dAttributes = "set_3d_attributes";
		public static readonly StringName Get3dAttributes = "get_3d_attributes";
		public static readonly StringName SetNodeAttributes = "set_node_attributes";
		public static readonly StringName SetCallback = "set_callback";
		public static readonly StringName SetProgrammerCallback = "set_programmer_callback";
		public static readonly StringName GetProgrammerCallbackSoundKey = "get_programmer_callback_sound_key";
		public static readonly StringName IsValid = "is_valid";
		public static readonly StringName Release = "release";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodEvent";

	#region Enums

	public enum FMOD_STUDIO_PLAYBACK_STATE : long
	{
		Playing = 0L,
		Sustaining = 1L,
		Stopped = 2L,
		Starting = 3L,
		Stopping = 4L,
		Forceint = 65536L,
	}

	#endregion

	#region Properties

	public bool Paused
	{
		get => (bool)_object.Get(PropertyName.Paused);
		set => _object.Set(PropertyName.Paused, value);
	}

	public float Pitch
	{
		get => (float)_object.Get(PropertyName.Pitch);
		set => _object.Set(PropertyName.Pitch, value);
	}

	public float Volume
	{
		get => (float)_object.Get(PropertyName.Volume);
		set => _object.Set(PropertyName.Volume, value);
	}

	public int Position
	{
		get => (int)_object.Get(PropertyName.Position);
		set => _object.Set(PropertyName.Position, value);
	}

	public int ListenerMask
	{
		get => (int)_object.Get(PropertyName.ListenerMask);
		set => _object.Set(PropertyName.ListenerMask, value);
	}

	public Godot.Transform2D Transform2d
	{
		get => (Godot.Transform2D)_object.Get(PropertyName.Transform2d);
		set => _object.Set(PropertyName.Transform2d, value);
	}

	public Godot.Transform3D Transform3d
	{
		get => (Godot.Transform3D)_object.Get(PropertyName.Transform3d);
		set => _object.Set(PropertyName.Transform3d, value);
	}

	#endregion

	#region Methods

	public float GetParameterByName(string @parameter_name)
	{
		return (float)_object.Call(MethodName.GetParameterByName, @parameter_name);
	}

	public void SetParameterByName(string @parameter_name, float @value)
	{
		_object.Call(MethodName.SetParameterByName, @parameter_name, @value);
	}

	public void SetParameterByNameWithLabel(string @parameter_name, string @label, bool @ignoreseekspeed)
	{
		_object.Call(MethodName.SetParameterByNameWithLabel, @parameter_name, @label, @ignoreseekspeed);
	}

	public float GetParameterById(int @parameter_id)
	{
		return (float)_object.Call(MethodName.GetParameterById, @parameter_id);
	}

	public void SetParameterById(int @parameter_id, float @value)
	{
		_object.Call(MethodName.SetParameterById, @parameter_id, @value);
	}

	public void SetParameterByIdWithLabel(int @parameter_id, string @label, bool @ignoreseekspeed)
	{
		_object.Call(MethodName.SetParameterByIdWithLabel, @parameter_id, @label, @ignoreseekspeed);
	}

	public void Start()
	{
		_object.Call(MethodName.Start);
	}

	public void Stop(int @stopMode)
	{
		_object.Call(MethodName.Stop, @stopMode);
	}

	public void EventKeyOff()
	{
		_object.Call(MethodName.EventKeyOff);
	}

	public FMOD_STUDIO_PLAYBACK_STATE GetPlaybackState()
	{
		return (FMOD_STUDIO_PLAYBACK_STATE)(int)_object.Call(MethodName.GetPlaybackState);
	}

	public bool GetPaused()
	{
		return (bool)_object.Call(MethodName.GetPaused);
	}

	public void SetPaused(bool @paused)
	{
		_object.Call(MethodName.SetPaused, @paused);
	}

	public float GetPitch()
	{
		return (float)_object.Call(MethodName.GetPitch);
	}

	public void SetPitch(float @pitch)
	{
		_object.Call(MethodName.SetPitch, @pitch);
	}

	public float GetVolume()
	{
		return (float)_object.Call(MethodName.GetVolume);
	}

	public void SetVolume(float @volume)
	{
		_object.Call(MethodName.SetVolume, @volume);
	}

	public int GetTimelinePosition()
	{
		return (int)_object.Call(MethodName.GetTimelinePosition);
	}

	public void SetTimelinePosition(int @position)
	{
		_object.Call(MethodName.SetTimelinePosition, @position);
	}

	public float GetReverbLevel(int @index)
	{
		return (float)_object.Call(MethodName.GetReverbLevel, @index);
	}

	public void SetReverbLevel(int @index, float @level)
	{
		_object.Call(MethodName.SetReverbLevel, @index, @level);
	}

	public bool IsVirtual()
	{
		return (bool)_object.Call(MethodName.IsVirtual);
	}

	public void SetListenerMask(int @mask)
	{
		_object.Call(MethodName.SetListenerMask, @mask);
	}

	public int GetListenerMask()
	{
		return (int)_object.Call(MethodName.GetListenerMask);
	}

	public void Set2dAttributes(Godot.Transform2D @position)
	{
		_object.Call(MethodName.Set2dAttributes, @position);
	}

	public Godot.Transform2D Get2dAttributes()
	{
		return (Godot.Transform2D)_object.Call(MethodName.Get2dAttributes);
	}

	public void Set3dAttributes(Godot.Transform3D @transform)
	{
		_object.Call(MethodName.Set3dAttributes, @transform);
	}

	public Godot.Transform3D Get3dAttributes()
	{
		return (Godot.Transform3D)_object.Call(MethodName.Get3dAttributes);
	}

	public void SetNodeAttributes(Node @transform)
	{
		_object.Call(MethodName.SetNodeAttributes, @transform);
	}

	public void SetCallback(Godot.Callable @callback, int @callbackMask)
	{
		_object.Call(MethodName.SetCallback, @callback, @callbackMask);
	}

	public void SetProgrammerCallback(string @p_programmers_callback_sound_key)
	{
		_object.Call(MethodName.SetProgrammerCallback, @p_programmers_callback_sound_key);
	}

	public string GetProgrammerCallbackSoundKey()
	{
		return (string)_object.Call(MethodName.GetProgrammerCallbackSoundKey);
	}

	public bool IsValid()
	{
		return (bool)_object.Call(MethodName.IsValid);
	}

	public void Release()
	{
		_object.Call(MethodName.Release);
	}

	#endregion

	#region Inherited Methods

	public bool InitRef()
	{
		return _object.InitRef();
	}

	public bool Reference()
	{
		return _object.Reference();
	}

	public bool Unreference()
	{
		return _object.Unreference();
	}

	public int GetReferenceCount()
	{
		return _object.GetReferenceCount();
	}

	public void Free()
	{
		_object.Free();
	}

	public string GetClass()
	{
		return _object.GetClass();
	}

	public bool IsClass(string @class)
	{
		return _object.IsClass(@class);
	}

	public void Set(Godot.StringName @property, Variant @value)
	{
		_object.Set(@property, @value);
	}

	public Variant Get(Godot.StringName @property)
	{
		return _object.Get(@property);
	}

	public void SetIndexed(Godot.NodePath @property_path, Variant @value)
	{
		_object.SetIndexed(@property_path, @value);
	}

	public Variant GetIndexed(Godot.NodePath @property_path)
	{
		return _object.GetIndexed(@property_path);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetPropertyList()
	{
		return _object.GetPropertyList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetMethodList()
	{
		return _object.GetMethodList();
	}

	public bool PropertyCanRevert(Godot.StringName @property)
	{
		return _object.PropertyCanRevert(@property);
	}

	public Variant PropertyGetRevert(Godot.StringName @property)
	{
		return _object.PropertyGetRevert(@property);
	}

	public void Notification(int @what, bool @reversed = false)
	{
		_object.Notification(@what, @reversed);
	}

	public override string ToString()
	{
		return _object.ToString();
	}

	public ulong GetInstanceId()
	{
		return _object.GetInstanceId();
	}

	public void SetScript(Variant @script)
	{
		_object.SetScript(@script);
	}

	public Variant GetScript()
	{
		return _object.GetScript();
	}

	public void SetMeta(Godot.StringName @name, Variant @value)
	{
		_object.SetMeta(@name, @value);
	}

	public void RemoveMeta(Godot.StringName @name)
	{
		_object.RemoveMeta(@name);
	}

	public Variant GetMeta(Godot.StringName @name, Variant @default = default)
	{
		return _object.GetMeta(@name, @default);
	}

	public bool HasMeta(Godot.StringName @name)
	{
		return _object.HasMeta(@name);
	}

	public Godot.Collections.Array<StringName> GetMetaList()
	{
		return _object.GetMetaList();
	}

	public void AddUserSignal(string @signal, Godot.Collections.Array @arguments = null)
	{
		@arguments ??= new();
		_object.AddUserSignal(@signal, @arguments);
	}

	public bool HasUserSignal(Godot.StringName @signal)
	{
		return _object.HasUserSignal(@signal);
	}

	public void RemoveUserSignal(Godot.StringName @signal)
	{
		_object.RemoveUserSignal(@signal);
	}

	public Godot.Error EmitSignal(Godot.StringName @signal, params Variant[] varargs)
	{
		return _object.EmitSignal(@signal, varargs);
	}

	public Variant Call(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.Call(@method, varargs);
	}

	public Variant CallDeferred(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallDeferred(@method, varargs);
	}

	public void SetDeferred(Godot.StringName @property, Variant @value)
	{
		_object.SetDeferred(@property, @value);
	}

	public Variant Callv(Godot.StringName @method, Godot.Collections.Array @arg_array)
	{
		return _object.Callv(@method, @arg_array);
	}

	public bool HasMethod(Godot.StringName @method)
	{
		return _object.HasMethod(@method);
	}

	public int GetMethodArgumentCount(Godot.StringName @method)
	{
		return _object.GetMethodArgumentCount(@method);
	}

	public bool HasSignal(Godot.StringName @signal)
	{
		return _object.HasSignal(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalList()
	{
		return _object.GetSignalList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalConnectionList(Godot.StringName @signal)
	{
		return _object.GetSignalConnectionList(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetIncomingConnections()
	{
		return _object.GetIncomingConnections();
	}

	public Godot.Error Connect(Godot.StringName @signal, Godot.Callable @callable, uint @flags = (uint)0)
	{
		return _object.Connect(@signal, @callable, @flags);
	}

	public void Disconnect(Godot.StringName @signal, Godot.Callable @callable)
	{
		_object.Disconnect(@signal, @callable);
	}

	public bool IsConnected(Godot.StringName @signal, Godot.Callable @callable)
	{
		return _object.IsConnected(@signal, @callable);
	}

	public bool HasConnections(Godot.StringName @signal)
	{
		return _object.HasConnections(@signal);
	}

	public void SetBlockSignals(bool @enable)
	{
		_object.SetBlockSignals(@enable);
	}

	public bool IsBlockingSignals()
	{
		return _object.IsBlockingSignals();
	}

	public void NotifyPropertyListChanged()
	{
		_object.NotifyPropertyListChanged();
	}

	public void SetMessageTranslation(bool @enable)
	{
		_object.SetMessageTranslation(@enable);
	}

	public bool CanTranslateMessages()
	{
		return _object.CanTranslateMessages();
	}

	public string Tr(Godot.StringName @message, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.Tr(@message, @context);
	}

	public string TrN(Godot.StringName @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.TrN(@message, @plural_message, @n, @context);
	}

	public Godot.StringName GetTranslationDomain()
	{
		return _object.GetTranslationDomain();
	}

	public void SetTranslationDomain(Godot.StringName @domain)
	{
		_object.SetTranslationDomain(@domain);
	}

	public bool IsQueuedForDeletion()
	{
		return _object.IsQueuedForDeletion();
	}

	public void CancelFree()
	{
		_object.CancelFree();
	}

	#endregion

	#region Inherited Signals

	public event Action ScriptChanged
	{
		add
		{
			Connect(SignalName.ScriptChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ScriptChanged, Callable.From(value));
		}
	}

	public event Action PropertyListChanged
	{
		add
		{
			Connect(SignalName.PropertyListChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.PropertyListChanged, Callable.From(value));
		}
	}

	#endregion
}
