// This code was automatically generated by GDExtension C# Bindgen
using System;
using System.Diagnostics.CodeAnalysis;
using Godot;

namespace GDExtensionBindgen;

public class FmodEventDescription
{
	// Engine object used for calling engine methods
	protected RefCounted _object;

	public FmodEventDescription() : this(NativeName)
	{
	}
	protected FmodEventDescription(StringName @class) : this(ClassDB.Instantiate(@class))
	{
	}
	protected FmodEventDescription(Variant variant) : this((RefCounted) variant)
	{
	}
	protected FmodEventDescription([NotNull] RefCounted @object)
	{
		_object = @object;
	}

	public static implicit operator RefCounted(FmodEventDescription self) => self?._object;
	public static implicit operator Variant(FmodEventDescription self) => self?._object;
	public static explicit operator FmodEventDescription(Variant variant) => variant.AsGodotObject() != null ? new(variant) : null;

	public class PropertyName : RefCounted.PropertyName
	{

	}

	public class MethodName : RefCounted.MethodName
	{
		public static readonly StringName GetLength = "get_length";
		public static readonly StringName GetInstanceList = "get_instance_list";
		public static readonly StringName GetInstanceCount = "get_instance_count";
		public static readonly StringName ReleaseAllInstances = "release_all_instances";
		public static readonly StringName LoadSampleData = "load_sample_data";
		public static readonly StringName UnloadSampleData = "unload_sample_data";
		public static readonly StringName GetSampleLoadingState = "get_sample_loading_state";
		public static readonly StringName Is3d = "is_3d";
		public static readonly StringName IsOneShot = "is_one_shot";
		public static readonly StringName IsSnapshot = "is_snapshot";
		public static readonly StringName IsStream = "is_stream";
		public static readonly StringName HasSustainPoint = "has_sustain_point";
		public static readonly StringName GetMinMaxDistance = "get_min_max_distance";
		public static readonly StringName GetSoundSize = "get_sound_size";
		public static readonly StringName GetParameterByName = "get_parameter_by_name";
		public static readonly StringName GetParameterById = "get_parameter_by_id";
		public static readonly StringName GetParameterCount = "get_parameter_count";
		public static readonly StringName GetParameterByIndex = "get_parameter_by_index";
		public static readonly StringName GetParameters = "get_parameters";
		public static readonly StringName GetParameterLabelById = "get_parameter_label_by_id";
		public static readonly StringName GetParameterLabelByName = "get_parameter_label_by_name";
		public static readonly StringName GetParameterLabelByIndex = "get_parameter_label_by_index";
		public static readonly StringName GetParameterLabelsById = "get_parameter_labels_by_id";
		public static readonly StringName GetParameterLabelsByName = "get_parameter_labels_by_name";
		public static readonly StringName GetParameterLabelsByIndex = "get_parameter_labels_by_index";
		public static readonly StringName GetUserProperty = "get_user_property";
		public static readonly StringName GetUserPropertyCount = "get_user_property_count";
		public static readonly StringName UserPropertyByIndex = "user_property_by_index";
		public static readonly StringName IsValid = "is_valid";
		public static readonly StringName GetPath = "get_path";
		public static readonly StringName GetGuid = "get_guid";
	}

	public class SignalName : RefCounted.SignalName
	{

	}

	private static readonly StringName NativeName = "FmodEventDescription";

	#region Methods

	public int GetLength()
	{
		return (int)_object.Call(MethodName.GetLength);
	}

	public Godot.Collections.Array GetInstanceList()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetInstanceList);
	}

	public int GetInstanceCount()
	{
		return (int)_object.Call(MethodName.GetInstanceCount);
	}

	public void ReleaseAllInstances()
	{
		_object.Call(MethodName.ReleaseAllInstances);
	}

	public void LoadSampleData()
	{
		_object.Call(MethodName.LoadSampleData);
	}

	public void UnloadSampleData()
	{
		_object.Call(MethodName.UnloadSampleData);
	}

	public int GetSampleLoadingState()
	{
		return (int)_object.Call(MethodName.GetSampleLoadingState);
	}

	public bool Is3d()
	{
		return (bool)_object.Call(MethodName.Is3d);
	}

	public bool IsOneShot()
	{
		return (bool)_object.Call(MethodName.IsOneShot);
	}

	public bool IsSnapshot()
	{
		return (bool)_object.Call(MethodName.IsSnapshot);
	}

	public bool IsStream()
	{
		return (bool)_object.Call(MethodName.IsStream);
	}

	public bool HasSustainPoint()
	{
		return (bool)_object.Call(MethodName.HasSustainPoint);
	}

	public Godot.Collections.Array GetMinMaxDistance()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetMinMaxDistance);
	}

	public float GetSoundSize()
	{
		return (float)_object.Call(MethodName.GetSoundSize);
	}

	public FmodParameterDescription GetParameterByName(string @name)
	{
		return (FmodParameterDescription)_object.Call(MethodName.GetParameterByName, @name);
	}

	public FmodParameterDescription GetParameterById(int @eventPathidPair)
	{
		return (FmodParameterDescription)_object.Call(MethodName.GetParameterById, @eventPathidPair);
	}

	public int GetParameterCount()
	{
		return (int)_object.Call(MethodName.GetParameterCount);
	}

	public FmodParameterDescription GetParameterByIndex(int @index)
	{
		return (FmodParameterDescription)_object.Call(MethodName.GetParameterByIndex, @index);
	}

	public Godot.Collections.Array GetParameters()
	{
		return (Godot.Collections.Array)_object.Call(MethodName.GetParameters);
	}

	public string GetParameterLabelById(int @_unnamed_arg0, int @_unnamed_arg1)
	{
		return (string)_object.Call(MethodName.GetParameterLabelById, @_unnamed_arg0, @_unnamed_arg1);
	}

	public string GetParameterLabelByName(string @_unnamed_arg0, int @_unnamed_arg1)
	{
		return (string)_object.Call(MethodName.GetParameterLabelByName, @_unnamed_arg0, @_unnamed_arg1);
	}

	public string GetParameterLabelByIndex(int @_unnamed_arg0, int @_unnamed_arg1)
	{
		return (string)_object.Call(MethodName.GetParameterLabelByIndex, @_unnamed_arg0, @_unnamed_arg1);
	}

	public string[] GetParameterLabelsById(int @_unnamed_arg0)
	{
		return (string[])_object.Call(MethodName.GetParameterLabelsById, @_unnamed_arg0);
	}

	public string[] GetParameterLabelsByName(string @_unnamed_arg0)
	{
		return (string[])_object.Call(MethodName.GetParameterLabelsByName, @_unnamed_arg0);
	}

	public string[] GetParameterLabelsByIndex(int @_unnamed_arg0)
	{
		return (string[])_object.Call(MethodName.GetParameterLabelsByIndex, @_unnamed_arg0);
	}

	public Godot.Collections.Dictionary GetUserProperty(string @name)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.GetUserProperty, @name);
	}

	public int GetUserPropertyCount()
	{
		return (int)_object.Call(MethodName.GetUserPropertyCount);
	}

	public Godot.Collections.Dictionary UserPropertyByIndex(int @index)
	{
		return (Godot.Collections.Dictionary)_object.Call(MethodName.UserPropertyByIndex, @index);
	}

	public bool IsValid()
	{
		return (bool)_object.Call(MethodName.IsValid);
	}

	public string GetPath()
	{
		return (string)_object.Call(MethodName.GetPath);
	}

	public string GetGuid()
	{
		return (string)_object.Call(MethodName.GetGuid);
	}

	#endregion

	#region Inherited Methods

	public bool InitRef()
	{
		return _object.InitRef();
	}

	public bool Reference()
	{
		return _object.Reference();
	}

	public bool Unreference()
	{
		return _object.Unreference();
	}

	public int GetReferenceCount()
	{
		return _object.GetReferenceCount();
	}

	public void Free()
	{
		_object.Free();
	}

	public string GetClass()
	{
		return _object.GetClass();
	}

	public bool IsClass(string @class)
	{
		return _object.IsClass(@class);
	}

	public void Set(Godot.StringName @property, Variant @value)
	{
		_object.Set(@property, @value);
	}

	public Variant Get(Godot.StringName @property)
	{
		return _object.Get(@property);
	}

	public void SetIndexed(Godot.NodePath @property_path, Variant @value)
	{
		_object.SetIndexed(@property_path, @value);
	}

	public Variant GetIndexed(Godot.NodePath @property_path)
	{
		return _object.GetIndexed(@property_path);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetPropertyList()
	{
		return _object.GetPropertyList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetMethodList()
	{
		return _object.GetMethodList();
	}

	public bool PropertyCanRevert(Godot.StringName @property)
	{
		return _object.PropertyCanRevert(@property);
	}

	public Variant PropertyGetRevert(Godot.StringName @property)
	{
		return _object.PropertyGetRevert(@property);
	}

	public void Notification(int @what, bool @reversed = false)
	{
		_object.Notification(@what, @reversed);
	}

	public override string ToString()
	{
		return _object.ToString();
	}

	public ulong GetInstanceId()
	{
		return _object.GetInstanceId();
	}

	public void SetScript(Variant @script)
	{
		_object.SetScript(@script);
	}

	public Variant GetScript()
	{
		return _object.GetScript();
	}

	public void SetMeta(Godot.StringName @name, Variant @value)
	{
		_object.SetMeta(@name, @value);
	}

	public void RemoveMeta(Godot.StringName @name)
	{
		_object.RemoveMeta(@name);
	}

	public Variant GetMeta(Godot.StringName @name, Variant @default = default)
	{
		return _object.GetMeta(@name, @default);
	}

	public bool HasMeta(Godot.StringName @name)
	{
		return _object.HasMeta(@name);
	}

	public Godot.Collections.Array<StringName> GetMetaList()
	{
		return _object.GetMetaList();
	}

	public void AddUserSignal(string @signal, Godot.Collections.Array @arguments = null)
	{
		@arguments ??= new();
		_object.AddUserSignal(@signal, @arguments);
	}

	public bool HasUserSignal(Godot.StringName @signal)
	{
		return _object.HasUserSignal(@signal);
	}

	public void RemoveUserSignal(Godot.StringName @signal)
	{
		_object.RemoveUserSignal(@signal);
	}

	public Godot.Error EmitSignal(Godot.StringName @signal, params Variant[] varargs)
	{
		return _object.EmitSignal(@signal, varargs);
	}

	public Variant Call(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.Call(@method, varargs);
	}

	public Variant CallDeferred(Godot.StringName @method, params Variant[] varargs)
	{
		return _object.CallDeferred(@method, varargs);
	}

	public void SetDeferred(Godot.StringName @property, Variant @value)
	{
		_object.SetDeferred(@property, @value);
	}

	public Variant Callv(Godot.StringName @method, Godot.Collections.Array @arg_array)
	{
		return _object.Callv(@method, @arg_array);
	}

	public bool HasMethod(Godot.StringName @method)
	{
		return _object.HasMethod(@method);
	}

	public int GetMethodArgumentCount(Godot.StringName @method)
	{
		return _object.GetMethodArgumentCount(@method);
	}

	public bool HasSignal(Godot.StringName @signal)
	{
		return _object.HasSignal(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalList()
	{
		return _object.GetSignalList();
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetSignalConnectionList(Godot.StringName @signal)
	{
		return _object.GetSignalConnectionList(@signal);
	}

	public Godot.Collections.Array<Godot.Collections.Dictionary> GetIncomingConnections()
	{
		return _object.GetIncomingConnections();
	}

	public Godot.Error Connect(Godot.StringName @signal, Godot.Callable @callable, uint @flags = (uint)0)
	{
		return _object.Connect(@signal, @callable, @flags);
	}

	public void Disconnect(Godot.StringName @signal, Godot.Callable @callable)
	{
		_object.Disconnect(@signal, @callable);
	}

	public bool IsConnected(Godot.StringName @signal, Godot.Callable @callable)
	{
		return _object.IsConnected(@signal, @callable);
	}

	public bool HasConnections(Godot.StringName @signal)
	{
		return _object.HasConnections(@signal);
	}

	public void SetBlockSignals(bool @enable)
	{
		_object.SetBlockSignals(@enable);
	}

	public bool IsBlockingSignals()
	{
		return _object.IsBlockingSignals();
	}

	public void NotifyPropertyListChanged()
	{
		_object.NotifyPropertyListChanged();
	}

	public void SetMessageTranslation(bool @enable)
	{
		_object.SetMessageTranslation(@enable);
	}

	public bool CanTranslateMessages()
	{
		return _object.CanTranslateMessages();
	}

	public string Tr(Godot.StringName @message, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.Tr(@message, @context);
	}

	public string TrN(Godot.StringName @message, Godot.StringName @plural_message, int @n, Godot.StringName @context = null)
	{
		@context ??= "";
		return _object.TrN(@message, @plural_message, @n, @context);
	}

	public Godot.StringName GetTranslationDomain()
	{
		return _object.GetTranslationDomain();
	}

	public void SetTranslationDomain(Godot.StringName @domain)
	{
		_object.SetTranslationDomain(@domain);
	}

	public bool IsQueuedForDeletion()
	{
		return _object.IsQueuedForDeletion();
	}

	public void CancelFree()
	{
		_object.CancelFree();
	}

	#endregion

	#region Inherited Signals

	public event Action ScriptChanged
	{
		add
		{
			Connect(SignalName.ScriptChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.ScriptChanged, Callable.From(value));
		}
	}

	public event Action PropertyListChanged
	{
		add
		{
			Connect(SignalName.PropertyListChanged, Callable.From(value));
		}
		remove
		{
			Disconnect(SignalName.PropertyListChanged, Callable.From(value));
		}
	}

	#endregion
}
